name: Sync Matches

on:
  schedule:
    # Executa todos os dias às 07:00 UTC (04:00 Horário de Brasília)
    - cron: '0 7 * * *'
  workflow_dispatch: # Permite executar o script manualmente pelo painel

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run GE Sync Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: go run cmd/sync/main.go

      - name: Run 365Scores Sync Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: go run cmd/sync365/main.go
